---
title: "Organizations and Management"
description: |
  Course website for Sociology 355, Duke University, Spring 2021
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```


## What is this course about?

This upper-division undergraduate course is about modern organizations and theories about how to manage them. 

Our focus is on for-profit firms. However we will also look at other organizations (e.g., churches, the state, unions, voluntary associations, social movements, and so on) as we go. We will explore different explanations of how organizations work, why they fail, how experts have said they should be managed, and how they connect with other aspects of social structure and culture. We will also critically examine the origins and development of the theories we read.

The course will give you a grounding in the sociology of organizations and teach you how to put these ideas to work both when analyzing real organizations and when navigating the vast scholarly and popular literature about them.

## Who is teaching it?

- _Instructor_: [Kieran Healy](https://kieranhealy.org). Email: `kieran.healy@duke.edu`. 
- _Teaching Assistant_: Andrew Carr.

## How will the course be taught?

This course is fully online. We will not meet in person and there is no assigned classroom. We meet on Wednesdays and Fridays from 12pm to 1:15pm.

Links to the course material will be provided via the [Sakai site](https://sakai.duke.edu/portal/directtool/a2eb6596-13e2-4578-a9ce-a822155e18e8/).

## What do I need to buy?

Most readings and other material will be provided via the Sakai site for the course. We will go through the details in class. We will also use some Harvard Business School Cases during the semester. These are available for purchase from [the HBS website for this course](https://hbsp.harvard.edu/import/788940).

## What do I need to do each week?

In general, _keep up_ with the reading; _watch_ and _take notes on_ any recorded lectures; _participate_ in the Friday discussions and tasks. Finally, _demonstrate_ that you understand what we've been discussing and can apply these ideas well.

Because the class will be fully online, after the first week we will divide the class days into two kinds. Each week I will record a lecture and make it available on the University's [WarpWire](https://launch.warpwire.duke.edu) service by Wednesday. There will be a link to each video from the [Sakai site](https://sakai.duke.edu/portal/directtool/a2eb6596-13e2-4578-a9ce-a822155e18e8/). You can watch the lecture during the designated class meeting time, or at any stage that's convenient to you. Once you've watched the lecture and done the readings, write your weekly brief and upload it to the class dropbox on Sakai. Briefs are due by 5pm Wednesday of each week. 

On Fridays, we will meet via Zoom to discuss the week's readings, the lecture, and your written briefs. I'll ask everyone to turn on their cameras so we can see one another. You should treat the Friday class as a kind of office hour, i.e. as a Q&A session and discussion opportunity. Its content will be driven by your questions in class and the content of the briefs you've written for that week. I expect you to come to class ready to ask questions and I'll call on people directly if there isn't a queue. Please take this process seriously and engage with it. The class will be _much_ better for everyone if you do.

### The recorded Wednesday lectures

The Wednesday lectures will not be simply a summary or rehashing of the reading material. Instead they will put the readings in context and develop and extend themes from them. They will also cover topics and examples _not_ discussed directly in the readings. 

### The format of the weekly brief

Your weekly brief should between 300 and 500 words long, no less and no more. It should focus on one of the starred readings for that week and do one or more of the following things:

- Connect the content of the starred reading to other readings for that week
- Raise a clear question about the reading that you want answered 
- Raise a question about how the content of this week's lecture relates to the reading
- Offer some coherent reflections on the content or the reading, perhaps by providing additional examples or extensions of the content based on your own thinking. 

When writing the brief, assume that the person reading it has also read the material. Your goal is not to summarize the reading but to reflect on it analytically, raise good questions, and facilitate or extend discussion about it.

## How will I be assessed?

You will be assessed by a number of short written assignments done prior to and during class, as well as your attendance and participation during discussion periods. From Week 2 onwards you will upload a brief of one of the starred readings (mainly HBS cases or items from the popular press). Briefs are due by 5pm Wednesday of each week.

There will also be a midterm exam and a final paper. Details on the paper's format and my expectations for it will be given in class.

Grades are computed as follows: 

- Participation: 40%
- Midterm: 30%
- Final paper: 30%


## What are the course policies?

- Notify me of absence due to illness or varsity sports travel _in advance_ where possible.
- Late assignments will not be accepted. 
- All assignments should be double-spaced, with 12-point font, and 1-inch margins.
- All assignments are individually written. Feel free to study and discuss the material with others in the class. All written work handed in must be your own, however.
- Suspected violations of academic integrity will be reported to the Dean’s Office. For more information on Duke University’s academic integrity policies, please refer to [university policy](https://studentaffairs.duke.edu/conduct).

## What are the readings and class schedule?

See the [Schedule page](schedule.html) for an overview of weekly readings and assignment due dates.

## Duke Community Standard

Like all classes at the university, this course is conducted under the Duke Community Standard. Duke University is a community dedicated to scholarship, leadership, and service and to the principles of honesty, fairness, respect, and accountability. Citizens of this community commit to reflect upon and uphold these principles in all academic and nonacademic endeavors, and to protect and promote a culture of integrity. To uphold the Duke Community Standard you will not lie, cheat, or steal in  academic endeavors; you will conduct yourself honorably in all your endeavors; and you will act if the Standard is compromised.

## Other resources

Any student requesting learning accommodations related to a disability or other condition is required to [register](https://trinity.duke.edu/undergraduate/academic-policies/academic-accommodations) with the SDA office and provide an accommodation notification, preferably within the first two weeks of class. All information will remain confidential.

